server:
  port: 2202

spring:
  profiles: dev

  application:
    name: service-ucenter
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.97.112.202:3307/sc_user?useUnicode=true&characterEncoding=utf-8
      username: yunche
      password: yc_123
      max-wait: 10000
      initialSize: 8
      min-idle: 0
      max-active: 20
      test-on-borrow: true

  redis:
    host: 47.97.112.202
    port: 6379
    password: yunche@1234
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 24
        max-wait: 2000

dubbo:
  application:
    name: service-ucenter
  registry:
    address: zookeeper://47.97.122.31:2181
  protocol:
    name: dubbo
    port: 28201
  provider:
    group: yunche
    version: 1.0.0


eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true      # 服务发现开关
    serviceUrl:              # Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
  instance:
    prefer-ip-address:  true  # 将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} # 指定实例id
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间

---

spring:
  profiles: prepub

  datasource:
    druid:
      url: jdbc:mysql://rm-bp1uk11f20h4i65u9oo.mysql.rds.aliyuncs.com:3306/yunche_user_center?useUnicode=true&characterEncoding=utf-8
      username: yuncheadmin
      password: ycjinfu@2099
      max-wait: 10000
      initialSize: 8
      min-idle: 0
      max-active: 8
      test-on-borrow: true

  redis:
    host: 47.97.122.31
    port: 6381
    password: yunche@1234
    timeout: 3000
    lettuce:
      pool:
        max-active: 50
        max-idle: 30
        min-idle: 0
        max-wait: 10000

dubbo:
  application:
    name: yunche-service-user-center-oauth
  registry:
    address: zookeeper://47.97.122.31:2181
  protocol:
    name: dubbo
    port: 28201
  provider:
    group: yunche
    version: 1.0.0


eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true      # 服务发现开关
    serviceUrl:              # Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
  instance:
    prefer-ip-address:  true  # 将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} # 指定实例id
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间


---

spring:
  profiles: pub

  datasource:
    druid:
      url: jdbc:mysql://rm-bp1uk11f20h4i65u9rw.mysql.rds.aliyuncs.com:3306/yunche_user_center?useUnicode=true&characterEncoding=utf-8
      username: yuncheadmin
      password: ycjinfu@2099
      max-wait: 10000
      initialSize: 16
      minIdle: 16
      max-active: 30
      test-on-borrow: true

  redis:
    host: r-bp1b3d268c17de84.redis.rds.aliyuncs.com
    port: 6379
    password: Yunche2018
    timeout: 3000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 500
        min-idle: 50
        max-wait: 5000


dubbo:
  application:
    name: service-ucenter-oauth
  registry:
    address: zookeeper://47.97.122.31:2181
  protocol:
    name: dubbo
    port: 28201
  provider:
    group: yunche
    version: 1.0.0


eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true      # 服务发现开关
    serviceUrl:              # Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
  instance:
    prefer-ip-address:  true  # 将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} # 指定实例id
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间