server:
  port: ${PORT:50101} #服务端口
spring:
#  profiles: dev
  application:
    name: govern-center # 指定服务名

eureka:
  client:
    registerWithEureka: true    # 服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true         # 服务发现，是否从Eureka中获取注册信息
    serviceUrl:                 # Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:${server.port}/eureka/}
  server:
    enable-self-preservation: false       # 是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000  # 服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    health-check-url-path: /actuator/health
    hostname: ${EUREKA_DOMAIN:127.0.0.1}
