spring:
  application:
    # Dubbo 应用名称
    ## 该值在 Dubbo Spring Cloud 加持下，被视作 dubbo.application.name
    ## 因此，无需再显示地配置 dubbo.application.name
    name: cloud-ali-api-dubbo-biz

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.2.14:3306/jzj_biz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: yunche
      password: yc_123
      max-wait: 10000
      initialSize: 4
      min-idle: 0
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 'X'

  redis:
    host: 192.168.2.18
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 24
        max-wait: 2000

dubbo:
  registry:

#    # zk
#    address: zookeeper://192.168.2.18:2181

#    # nacos
#    address: nacos://127.0.0.1:8848

    # 将Dubbo的注册中心 挂载到 SpringCloud的注册中心上
    address: spring-cloud://localhost
#  cloud:
#    # 不推荐使用默认值为 "*"，它将订阅所有应用
#    subscribed-services: cloud-ali-svc-dubbo-storage,cloud-ali-svc-dubbo-account,cloud-ali-svc-dubbo-order,cloud-ali-svc-dubbo-user
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  consumer:
    group: bebopze
    version: 1.0.0
    timeout: 30000

# swagger-ui
swagger-ui.open: true