spring:
  application:
    name: cloud-ali-svc-biz

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.2.14:3306/jzj_biz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: yunche
      password: yc_123
      max-wait: 10000
      initialSize: 4
      min-idle: 0
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 'X'

  redis:
    host: 192.168.2.18
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 24
        max-wait: 2000

dubbo:
  application:
    name: ${spring.application.name}
  registry:
#    # zk
#    address: zookeeper://192.168.2.18:2181
#    # nacos
#    address: nacos://127.0.0.1:8848
    ## The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost
#  cloud:
#    ##  默认"*"： subscribe all providers
#    ##  指定services：subscriber specifies the required providers.
#    # The subscribed services in consumer side
#    subscribed-services: cloud-ali-svc-storage,cloud-ali-svc-account,cloud-ali-svc-order
  protocol:
    name: dubbo
    port: -1
  consumer:
    group: junzijian
    version: 1.0.0
    timeout: 30000

# swagger-ui
swagger-ui.open: true