server:
  port: 8091

spring:
  application:
    name: govern-gateway-spring-cloud-gateway

  # redis
  redis:
    host: 47.97.112.202
    port: 6379
    password: yunche@1234
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 24
        max-wait: 2000

#  zipkin:
#    enabled: true
#    sender:
#      type: rabbit
#    sleuth:
#      enabled: true
#      http:
#        legacy:
#          enabled: true
#    #jwt密码
#    security:
#      oauth2:
#        jwt:
#          signingKey: 123456
  cloud:
    # gateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # cors
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      # default-filters
      default-filters:
      - StripPrefix=1          # 去除prefix：/api
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      # 移除请求的头部Origin  当该请求不是一个CORS请求（即不包含头部Origin），处理的过程就结束，这样可以避免后续的检查
      - RemoveRequestHeader=Origin
      - name: Hystrix
        args:
          name: fallbackcmd
          fallbackUri: forward:/fallbackcontroller?a=123
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 1000  # 令牌桶的容积
          redis-rate-limiter.burstCapacity: 1     # 流速 每秒
          rate-limiter: "#{@defaultRedisRateLimiter}"  # SPEL表达式去的对应的bean
          key-resolver: "#{@apiKeyResolver}" # SPEL表达式去的对应的bean
      # router
      routes:
      # =====================================
      - id: api-business-web
        uri: lb://api-business-web
        predicates:
        - Path=${server.servlet.context-path}/biz/web/**
        filters:
#        - PrefixPath=/v1     # 添加prefix  /api/biz/web/v1
#        - StripPrefix=1      # 去除prefix  /biz/web
        - AddResponseHeader=foo, bar
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
      # =====================================
      - id: api-business-app
        uri: lb://api-business-app
        predicates:
        - Path=${server.servlet.context-path}/biz/app/**
        filters:
        - AddResponseHeader=foo, bar
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
      # =====================================
      - id: api-business-alipay-life
        uri: lb://api-business-alipay-life
        predicates:
        - Path=${server.servlet.context-path}/biz/alipay/life/**
        filters:
        - AddResponseHeader=foo, bar
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY

# eureka
eureka:
  client:
    registerWithEureka: true  # 服务注册开关
    fetchRegistry: true       # 服务发现开关
    serviceUrl:               # Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}

# 网关白名单，无需要签权url
gate:
 ignore:
   authentication:
     startWith: /oauth,/open

#management.endpoints.web.exposure.include: '*'
